#!/usr/bin/perl
#
# Copyright (c) 2019-2020, AT&T Intellectual Property. All rights reserved.
#
# SPDX-License-Identifier: GPL-2.0-only
#

use strict;
use warnings;
use File::Slurp qw(read_file);

use lib "/opt/vyatta/share/perl5/";
use Vyatta::Syslog;

sub usage {
    print <<EOF;
Usage: <device>
EOF
    exit 1;
}

my $dev = shift;

usage() unless defined($dev);

foreach my $line ( read_file( $SOURCE_INTERFACE_FILE, 'err_mode' => 'quiet' ) )
{
    chomp($line);
    my $sdev = ( split( ' ', $line ) )[0];
    if ( $sdev eq $dev ) {
        my $addrs = `ip -6 addr show scope global dev $sdev`;
        if ( !$addrs ) {
            update_rsyslog_config();
            last;
        }
    }
}

exit 0;
